name: Build Custom RustDesk
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout source & pull submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Inject custom server & public key (PowerShell版本，Windows环境)
        run: |
          $filePath = "libs/hbb_common/src/config.rs"
          $content = Get-Content $filePath -Raw
          #替换ID服务器
          $content = $content -replace 'pub const RENDEZVOUS_SERVERS: &\[&str\] = &\[.*\];', "pub const RENDEZVOUS_SERVERS: &[&str] = &[\"${{ secrets.RENDEZVOUS_SERVER }}\"];"
          #替换公钥
          $content = $content -replace 'pub const RS_PUB_KEY: &str = ".*";', "pub const RS_PUB_KEY: &str = `"${{ secrets.RS_PUB_KEY }}`";"
          Set-Content $filePath $content
        shell: pwsh

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          cache: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build RustDesk Windows
        run: |
          cd flutter
          flutter pub get
          flutter build windows --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-win-custom
          path: flutter/build/windows/x64/runner/Release/
